### ISSUE TITLE
How to keep the server running?

### ISSUE THREAD

**Issue by VeeK727** [andyet/signalmaster#100]
I have successfully setup my server and it's working fine. i did it using PuTTY on windows to ssh into my ubuntu server and did all the setup as explained in the docs.

However, if I now close PuTTY, the server goes down. I can't keep the SSH window open forever on my personal computer, how do I keep the server running in the background?

**Comment by artofspeed** [comment]
use pm2

**Comment by VeeK727** [comment]
That worked. Thanks. If anyone looking for the same thing, here's what I used (3 commands)

```
NODE_ENV=production pm2 start server.js
pm2 startup systemd ubuntu
pm2 save
```
