### ISSUE TITLE
Port 8888 is not for WebRTC signaling servers

### ISSUE THREAD

**Issue by pfifo** [andyet/signalmaster#104]
Port 8888 is generally used for http proxy servers
Running anything on 8888 is a security flaw

Defaulting to 8888 out of habit is bad coding practice.

**Comment by evilpacket** [comment]
@pfifo Thank you for your concern but this is not a security flaw as it does not create any risk for the user of this software by having this potential port confusion. 

The default port is configurable via the configuration found in the config/production.json or config/development.json
