### ISSUE TITLE
WebSocket connection failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by diliptrainee** [andyet/signalmaster#119]
Hi, i am getting WebSocket connection to 'wss://mydomain:<8888>/socket.io/?EIO=3&transport=websocket&sid=K53lITpUNyWpHoPBAAAD' failed: WebSocket is closed before the connection is established.
I have deployed signalling server on AWS Ubuntu OS,when i tested it is displaying "signal master is running at: http://localhost:8888" 
Applied SSl and when i tested from browser https://<mydomain>:<8888>/socket.io/ ,it displayed 
{"code":0,"message":"Transport unknown"}.
When i used the same signalling url : https://<mydomain>:<8888>/ in simplewebrtc configuration file it is giving 'wss://<mydomain>:<8888>/socket.io/?EIO=3&transport=websocket&sid=K53lITpUNyWpHoPBAAAD' failed: WebSocket is closed before the connection is established.

I have deployed Coturn- TURN SERVER as well on AWS and used the turn server configuration in signalling server production.js file.

Socket.io version in signalling server is : 1.7.4
socket.io-client : 2.0.4,
express : 4.14.0

**Comment by diliptrainee** [comment]
Followed the below link.worked like charm...
https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon

**Comment by musicformellons** [comment]
Which answer worked? The one adding ```{transports: ['websocket']}``` ?
