### ISSUE TITLE
move stun/turn config to new .urls syntax

### ISSUE THREAD

**Issue by fippo** [andyet/signalmaster#14]
the stun/turn config in dev_config.json currently uses .url to specify the stun/turn url. The spec now says this should be .urls so we should use that as well.
Needs to be checked in chrome and firefox

**Comment by jfs77** [comment]
Hi,

I use xirsys Turn server. I would like to configure turn server like this : 
credential :"2551d1a4-xxxx-xxxx-xxxx-xxxxxxxx2199"
username :"1_25xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxc919"
"uris" : [
     "turn:turn02.uswest.xirsys.com:443?transport=udp",
      "turn:turn02.uswest.xirsys.com:443?transport=tcp",
      "turn:turn02.uswest.xirsys.com:5349?transport=udp",
      "turn:turn02.uswest.xirsys.com:5349?transport=tcp" 
]

its doesnt work. Is it the goog way ?

**Comment by fippo** [comment]
@jfs77 this won't work in Firefox yet (it soon might in a new version of simplewebrtc), so you'll have to implement this on your own.

**Comment by fippo** [comment]
fixed by #48
