### ISSUE TITLE
Install fails on Cloudcontrol and Heroku

### ISSUE THREAD

**Issue by OpenHaus** [andyet/signalmaster#3]
I am getting a weired error when I try to deploy your package on one of the above cloud services. Any idea why? I could not figure it out. Below you find the installation log from Heroku.

Please see http://textsave.de/?p=169065 for the complete log. It was too long to post here.

**Comment by dtsdwarak** [comment]
@OpenHaus : I think it does perfectly. You'd have to modify the ```dev_config.json``` file for appropriate settings. I have forked the same and have a working copy at [@dtsdwarak/webrtc-signal](https://github.com/dtsdwarak/webrtc-signal).

**Comment by bear** [comment]
signalmaster is a stock NodeJS app. 

As @dtsdwarak mentions - you *have* to edit the dev_config.json at a minimum to remove the comments and adjust the settings.

I'm going to close this - please do reopen with an error log snippe if needed (the link you gave showed no log lines)
