### ISSUE TITLE
only  logged JWT  verified users

### ISSUE THREAD

**Issue by poshetz** [andyet/signalmaster#34]
Is it possible to run the signalmaster only for users who are JWT verified?

I need only logged users to be in chat, is it possible somehow without having to rewrite the server.js file?

thanks a lot!

**Comment by fippo** [comment]
you'll need something like https://gith ub.com/auth0/socketio-jwt (but make sure whatever you use has addressed the recent jwt vulnerability) -- signalmaster is just using socket.io

**Comment by poshetz** [comment]
@fippo  thanks a lot :) i am going to open a new issue i found some problems with CPU :(
