### ISSUE TITLE
Signaling-master is not working with SimpleWebRTC-master on localhost.

### ISSUE THREAD

**Issue by Jp2016** [andyet/signalmaster#60]
I am not able to connect user. 

issue is there i can't see peer remote connection.

Connection is not happening between users.

I have attach one screenshot about the console error look at the following screen shot.

![screenshot_2](https://cloud.githubusercontent.com/assets/16609014/12256915/9d382d76-b927-11e5-8d7a-77dc3a029906.png)

**Comment by weinrank** [comment]
Which version of Socket.io are you running? I saw a similar error with 1.4 while 1.3.7 is fine.

**Comment by Jp2016** [comment]
Thanks for your advise.

Yes this is problem of version of socket.io.

Now its working fine.

Thanks for that.

Have a good day..
