### ISSUE TITLE
Installing Signalmaster on production server 

### ISSUE THREAD

**Issue by Oluwafemikorede** [andyet/signalmaster#67]
hello,

I installed signalmaster on my centos and I tried running node server.js and it shows server runs on localhost:8888, how do I change my config or settings to make server reflect my production url

**Comment by fippo** [comment]
the server should be listening on all interface by default -- https://github.com/andyet/signalmaster/blob/master/server.js#L29-L34 is slightly misleading about that.

Typically you will want to run this behind nginx or haproxy. See the [socket.io documentation](http://socket.io/docs/using-multiple-nodes/) for this

**Comment by Oluwafemikorede** [comment]
@fippo will changing https://localhost: on https://github.com/andyet/signalmaster/blob/master/server.js#L29-L34   to my url resolve the issue?

And how can I "run this behind nginx or haproxy."

**Comment by fippo** [comment]
there should be no issue, you can ignore console.log output

**Comment by xdumaine** [comment]
You don't need to change that, it's just a logged value. It's already listening on the interface. Provided your DNS is configured, your URL will work.

**Comment by Oluwafemikorede** [comment]
I followed the installation steps but I am not getting "Welcome to socket.io" when I point my browser to the url, any reason why this might be happening

**Comment by fippo** [comment]
the README is outdated :-(
If you get a
```{"code":0,"message":"Transport unknown"}```

from http://yourservernamehere:8888/socket.io/ you should be good

**Comment by Oluwafemikorede** [comment]
thanks, it works, so my signalling service will now be something like this right... 

http://yourservernamehere:8888/

but how do I change it to https, running this command 

./scripts/generare-ssl-certs.sh 

throws this error

-bash: ./scripts/generare-ssl-certs.sh: No such file or directory

**Comment by Oluwafemikorede** [comment]
thnaks, all problem fixed now, I think the documentation needs to be updated. You can close the issue now.

**Comment by canturker** [comment]
@Oluwafemikorede how can you solved issue? I have same problem and cant find solution
