### ISSUE TITLE
I get 404

### ISSUE THREAD

**Issue by kostaspapas** [andyet/signalmaster#81]
Hello there,

- I have git clone signalmaster on Centos 6 ( on an virtual machine)

sudo git clone https://github.com/andyet/signalmaster.git signalmaster
- cd signalmaster
- sudo npm install
- sudo npm install async
- sudo npm install redis 
- sudo npm install underscore

So, now I have these versions :

precommit-hook 0.3.10
getconfing 2.1.0
node-uuid 1.2.0
yetify 0.0.1
tape 2.14.1
socket.io 1.3.7
socket.io-client 1.3.7
async 1.5.2
redis 2.5.1
underscore 1.8.3

- sudo node server.js

I get message

&yet -- signal master is running at: http://localhost:8888

- Using mozilla on Centos 6 (Virtual machine Virtual box) I type:

http://localhost:8888
and I get 
status code : 404 Not Found

What it's wrong?

I have already read issues "#73 Why are not npm packages in the package.json dependencies?" and "#53 Missing Welcome and Transport Unknown"

Thank you in advance
Kostas

**Comment by Maykonn** [comment]
Me too

**Comment by railsfactory-kumaresan** [comment]
+1

**Comment by fippo** [comment]
the README is outdated. Check http://localhost:8888/socket.io/ which should give you a socket.io-ish error message.
