### ISSUE TITLE
How do I check if signalmaster is using my TURN server?

### ISSUE THREAD

**Issue by think123** [andyet/signalmaster#86]
I have this section of code inside my `production.json`:

```
"turnservers": [
    {
      "urls": ["turn:www.tuotr.com:8080"],
      "secret": "turnserversharedsecret",
      "expiry": 86400
    }
  ]
```

And the video seemed to be working fine in my simpleWebRTC program, but then I realised that my restund TURN server was on port 3478, not 8080.

How do I check if signalmaster is using my TURN server, rather than the default TURN server it is using (I think the default is the sandboxed one?)

**Comment by v29neil** [comment]
how did you check it ?
