### ISSUE TITLE
Modify RTCSessionDescription

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/signalmaster#88]
Related to https://github.com/andyet/SimpleWebRTC/issues/436

Where can i tweak the offer or answer before it is set as the local or remote description by editing the values in the SDP text?
I could not find any RTCSessionDescription object.

**Comment by fippo** [comment]
https://github.com/andyet/signalmaster/blob/master/sockets.js#L15-L24 -- somewhere here. I think the message.type will be offer/answer

**Comment by Hirtenknogger** [comment]
@fippo thanks!
